# Warning: This config does not include keys that have an unset value
# ~/.config/starship.toml

format = '''\[$time\] $status$cmd_duration$username@$hostname \[$directory\] $python$java$nodejs$ruby$rust$ocaml$lua$kotlin$dart$php$elixir$git_branch$git_commit$git_status
[❯ ](bold green)'''
scan_timeout = 30
command_timeout = 500
add_newline = true

[cmd_duration]
min_time = 2000
format = '\([$duration]($style)\) '
style = 'yellow bold'
show_milliseconds = true
disabled = false
show_notifications = false
min_time_to_notify = 45000

[crystal]
format = 'via [$symbol($version )]($style)'
symbol = '🔮 '
style = 'bold red'

[dart]
format = 'via [$symbol$version]($style)'
symbol = '🎯 '
style = 'bold blue'

[deno]
format = 'via [$symbol$version]($style)'
symbol = '🦕 '
style = 'green bold'

[directory]
truncation_length = 3
truncate_to_repo = true
fish_style_pwd_dir_length = 0
use_logical_path = true
format = '[$path]($style)[$read_only]($read_only_style)'
style = 'fg:85 bold'
disabled = false
read_only = '🔒'
read_only_style = 'red'
truncation_symbol = '.../'
home_symbol = '~'

[docker_context]
symbol = '🐳 '
style = 'blue bold'
format = 'via [$symbol$context]($style) '

[dotnet]
format = '[$symbol($version )(🎯 $tfm )]($style)'
symbol = '.NET '
style = 'blue bold'

[elixir]
format = 'via [$symbol($version \(OTP $otp_version\) )]($style)'
symbol = '💧 '
style = 'bold purple'

[elm]
format = 'via [$symbol($version )]($style)'
symbol = '🌳 '
style = 'cyan bold'

[env_var]
symbol = ''
style = 'black bold dimmed'
format = 'with [$env_value]($style) '

[erlang]
format = 'via [$symbol($version )]($style)'
symbol = ' '
style = 'bold red'

[gcloud]
format = 'on [$symbol$account(\($region\))]($style) '
symbol = '☁️ '
style = 'bold blue'

[git_commit]
format = '[\($hash$tag\)]($style) '
style = 'green bold'

[git_state]
rebase = 'REBASING'
merge = 'MERGING'
revert = 'REVERTING'
cherry_pick = 'CHERRY-PICKING'
bisect = 'BISECTING'
am = 'AM'
am_or_rebase = 'AM/REBASE'
style = 'bold yellow'
format = '\([$state( $progress_current/$progress_total)]($style)\) '

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
style = 'red bold'

[golang]
format = 'via [$symbol($version )]($style)'
symbol = '🐹 '
style = 'bold cyan'

[helm]
format = 'via [$symbol($version )]($style)'
symbol = '⎈ '
style = 'bold white'

[hg_branch]
symbol = ' '
style = 'bold purple'
format = 'on [$symbol$branch]($style) '
truncation_length = 9223372036854775807
truncation_symbol = '…'
disabled = true

[hostname]
ssh_only = false
trim_at = '.'
format = '[$hostname]($style)'
style = 'fg:81 bold'
disabled = false

[java]
format = "[${symbol}(${version} )]($style)"
symbol = " "
style = 'red dimmed'

[julia]
format = 'via [$symbol($version )]($style)'
symbol = 'ஃ '
style = 'bold purple'

[kotlin]
format = 'via [$symbol($version )]($style)'
symbol = '🅺 '
style = 'bold blue'

[kubernetes]
symbol = '☸ '
format = '[$symbol$context( \($namespace\))]($style) in '
style = 'cyan bold'

[lua]
format = 'via [$symbol($version )]($style)'
symbol = '🌙 '
style = 'bold blue'

[memory_usage]
format = 'via $symbol[$ram( | $swap)]($style) '
style = 'white bold dimmed'
symbol = '🐏 '

[nim]
format = 'via [$symbol($version )]($style)'
symbol = '👑 '
style = 'yellow bold'

[nix_shell]
format = 'via [$symbol$state( \($name\))]($style) '
symbol = '❄️  '
style = 'bold blue'

[nodejs]
format = 'via [$symbol($version )]($style)'
symbol = ' '
style = 'bold green'

[ocaml]
format = 'via [$symbol($version )(\($switch_indicator$switch_name\) )]($style)'
symbol = '🐫 '
style = 'bold yellow'

[openstack]
format = '[$symbol$cloud(\($project\))]($style) '
symbol = '☁️  '
style = 'bold yellow'

[package]
format = "[$symbol$version]($style)"
symbol = '📦 '
style = '208 bold'

[perl]
symbol = '🐪 '
style = '149 bold'
format = 'via [$symbol($version )]($style)'

[php]
format = "[$symbol($version )]($style)"
symbol = " "
style = '147 bold'

[purescript]
format = 'via [$symbol$version]($style)'
symbol = '<=> '
style = 'bold white'

[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
symbol = " "

[red]
format = "[$symbol$version]($style)"
symbol = "🔺"
style = 'red bold'

[ruby]
format = "[$symbol$version]($style)"
symbol = "💎"
style = 'bold red'

[rust]
format = "[$symbol$version]($style)"
symbol = "🦀"
style = 'bold red'

[scala]
format = "[$symbol$version]($style)"
style = 'red bold'
symbol = "🆂 "

[shell]
format = '$indicator '
bash_indicator = 'bsh'
fish_indicator = 'fsh'
zsh_indicator = 'zsh'
powershell_indicator = 'psh'
ion_indicator = 'ion'
elvish_indicator = 'esh'
tcsh_indicator = 'tsh'

[shlvl]
threshold = 2
format = '[$symbol$shlvl]($style) '
symbol = '↕️  '
repeat = false
style = 'bold yellow'

[singularity]
symbol = ''
format = '[$symbol\[$env\]]($style) '
style = 'blue bold dimmed'

[status]
format = '[status](bright-red): [$status]($style) '
symbol = '✖'
not_executable_symbol = '🚫'
not_found_symbol = '🔍'
sigint_symbol = '🧱'
signal_symbol = '⚡'
style = 'bold red'
map_symbol = false
recognize_signal_code = true

[swift]
format = 'via [$symbol($version )]($style)'
symbol = '🐦 '
style = 'bold 202'

[terraform]
format = 'via [$symbol$workspace]($style) '
symbol = '💠 '
style = 'bold 105'

[time]
format = '[$time]($style)'
style = 'bold fg:202'
use_12hr = false
disabled = false
utc_time_offset = 'local'
time_range = '-'
time_format = '%T %d/%m'

[username]
format = '[$user]($style)'
style_root = 'fg:190 bold'
style_user = 'fg:226 bold'
show_always = true
disabled = false

[vagrant]
format = 'via [$symbol($version )]($style)'
symbol = '⍱ '
style = 'cyan bold'

[zig]
format = 'via [$symbol($version )]($style)'
symbol = '↯ '
style = 'bold yellow'

[custom]
